// Parity test between the web engine (js/*.js, untouched) and the mobile
// Dart rule engine (apps/mobile/lib/domain/rules/, data/engine-rules.json).
//
// The fixture (test/fixtures/engine_parity.json) is generated by
// scripts/generate-mobile-fixtures.mjs, which imports and runs the real,
// unmodified js/calendar-engine.js - it is the oracle here, not a hand-typed
// expectation, so it stays honest about what the web engine actually does
// today (see docs/gcal-calculation-comparison.md "Mobile app parity" for the
// known open discrepancies this is meant to close over time).
//
// Phase A scope only: masa adhika/kshaya/normal classification. Later
// phases add Ekadashi classification, parana window selection, and event
// matching to this same file.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:vcalendar_mobile/domain/models/calendar_location.dart';
import 'package:vcalendar_mobile/domain/models/panchanga_day.dart';
import 'package:vcalendar_mobile/domain/services/ekadashi_classifier.dart';
import 'package:vcalendar_mobile/domain/services/masa_rule_validator.dart';
import 'package:vcalendar_mobile/domain/services/panchanga_calculator.dart';
import 'package:vcalendar_mobile/domain/services/parana_engine.dart';

// Mirrors the coordinates in js/locations-data.js for exactly the location
// ids used by scripts/generate-mobile-fixtures.mjs. Kept local to this test
// (rather than reading js/locations-data.js) since it's a fixed, small,
// rarely-changing set and this test should not depend on parsing JS.
const _locations = <String, CalendarLocation>{
  'maalot': CalendarLocation(
    id: 'maalot',
    name: 'Maalot, Israel',
    countryName: 'Israel',
    timezone: 'Asia/Jerusalem',
    latitude: 33.016,
    longitude: 35.277,
    weekStart: 0,
  ),
  'tel-aviv': CalendarLocation(
    id: 'tel-aviv',
    name: 'Tel Aviv, Israel',
    countryName: 'Israel',
    timezone: 'Asia/Jerusalem',
    latitude: 32.0853,
    longitude: 34.7818,
    weekStart: 0,
  ),
  'mayapur': CalendarLocation(
    id: 'mayapur',
    name: 'Mayapur, India',
    countryName: 'India',
    timezone: 'Asia/Kolkata',
    latitude: 23.4241,
    longitude: 88.3883,
    weekStart: 0,
  ),
  'nabadwip': CalendarLocation(
    id: 'nabadwip',
    name: 'Nabadwip, India',
    countryName: 'India',
    timezone: 'Asia/Kolkata',
    latitude: 23.4067,
    longitude: 88.3686,
    weekStart: 0,
  ),
  'kathmandu': CalendarLocation(
    id: 'kathmandu',
    name: 'Kathmandu, Nepal',
    countryName: 'Nepal',
    timezone: 'Asia/Kathmandu',
    latitude: 27.7172,
    longitude: 85.324,
    weekStart: 1,
  ),
  'vrindavan': CalendarLocation(
    id: 'vrindavan',
    name: 'Vrindavan, India',
    countryName: 'India',
    timezone: 'Asia/Kolkata',
    latitude: 27.565,
    longitude: 77.6593,
    weekStart: 0,
  ),
};

void main() {
  late Map<String, dynamic> engineRules;
  late List<dynamic> fixtureCases;

  setUpAll(() {
    final engineRulesFile = File('../../data/engine-rules.json');
    engineRules = Map<String, dynamic>.from(
      jsonDecode(engineRulesFile.readAsStringSync()) as Map,
    );
    final fixtureFile = File('test/fixtures/engine_parity.json');
    final fixture = Map<String, dynamic>.from(
      jsonDecode(fixtureFile.readAsStringSync()) as Map,
    );
    fixtureCases = fixture['cases'] as List<dynamic>;
    // Fail loudly (not silently skip) if the fixture is missing/empty -
    // that means someone needs to re-run scripts/generate-mobile-fixtures.mjs.
    expect(
      fixtureCases,
      isNotEmpty,
      reason:
          'engine_parity.json fixture is empty - run '
          'node scripts/generate-mobile-fixtures.mjs from the repo root.',
    );
  });

  group('Phase A - masa classification', () {
    test(
      'rule-table classification agrees with PanchangaCalculator\'s own thresholds '
      '(self-consistency: same sankranti_count in, same type out)',
      () {
        final validator = MasaRuleValidator(engineRules);
        expect(validator.classifyBySankrantiCount(0), 'adhika');
        expect(validator.classifyBySankrantiCount(1), 'normal');
        expect(validator.classifyBySankrantiCount(2), 'kshaya');
      },
    );

    test(
      'Dart-computed masa type matches the web-engine fixture across all sampled days',
      () {
        final validator = MasaRuleValidator(engineRules);
        const calculator = PanchangaCalculator();
        final mismatches = <String>[];
        var checked = 0;

        for (final rawCase in fixtureCases) {
          final fixtureCase = Map<String, dynamic>.from(rawCase as Map);
          final locationId = fixtureCase['location_id'] as String;
          final location = _locations[locationId];
          if (location == null) continue;

          final dateParts = (fixtureCase['date'] as String)
              .split('-')
              .map(int.parse)
              .toList(growable: false);
          final date = DateTime.utc(
            dateParts[0],
            dateParts[1],
            dateParts[2],
          );

          final day = calculator.calculateDay(date: date, location: location);
          final expectedType =
              (fixtureCase['masa'] as Map)['type'] as String;

          checked += 1;

          // Self-consistency: the rule table must agree with Dart's own
          // sankranti_count for this exact day (independent of web).
          if (day.masaSankrantiCount != null) {
            final ruleTableType = validator.classifyBySankrantiCount(
              day.masaSankrantiCount!,
            );
            expect(
              ruleTableType,
              day.masaType,
              reason:
                  'rule table vs PanchangaCalculator disagree for '
                  '$locationId ${fixtureCase['date']}',
            );
          }

          // Cross-platform parity: Dart's own astronomy vs the web fixture.
          if (day.masaType != expectedType) {
            mismatches.add(
              '$locationId ${fixtureCase['date']}: dart=${day.masaType} web=$expectedType',
            );
          }
        }

        // Masa type only changes right at a new-moon/sankranti boundary, so
        // a handful of mismatches on exactly those boundary days (due to the
        // two platforms' independent astronomy libraries disagreeing by
        // minutes right at the crossing) is expected, not a bug. A high
        // mismatch rate would mean the classification logic itself is wrong.
        final mismatchRate = mismatches.length / checked;
        expect(
          mismatchRate,
          lessThan(0.02),
          reason:
              'Too many masa-type mismatches between Dart and web '
              '(${mismatches.length}/$checked):\n${mismatches.join('\n')}',
        );
      },
    );
  });

  group('Phase B - parana window', () {
    test(
      'ParanaEngine reproduces the web fixture\'s parana window for every '
      'sampled Ekadashi fast day (within a 2-minute astronomy-library tolerance)',
      () {
        final paranaEngine = ParanaEngine(engineRules);
        const calculator = PanchangaCalculator();
        final mismatches = <String>[];
        var checked = 0;

        for (final rawCase in fixtureCases) {
          final fixtureCase = Map<String, dynamic>.from(rawCase as Map);
          final locationId = fixtureCase['location_id'] as String;
          final location = _locations[locationId];
          if (location == null) continue;

          for (final rawEvent in fixtureCase['events'] as List) {
            final event = Map<String, dynamic>.from(rawEvent as Map);
            if (event['type'] != 'ekadashi') continue;

            checked += 1;
            final fastDateParts = (event['fast_date'] as String)
                .split('-')
                .map(int.parse)
                .toList(growable: false);
            final fastDate = DateTime.utc(
              fastDateParts[0],
              fastDateParts[1],
              fastDateParts[2],
            );
            final targetNumber = (event['target_number'] as num).toInt();
            // buildEkadashiEvent feeds computeParana the event's parana_type,
            // falling back to fast_day_type only when parana_type is absent -
            // see js/ekadashi-engine.js:283-286 and the ParanaEngine doc comment.
            final fastDayType =
                (event['parana_type'] as String?) ??
                event['fast_day_type'] as String;

            final result = paranaEngine.compute(
              fastDate: fastDate,
              ekadashiNumber: targetNumber,
              fastDayType: fastDayType,
              location: location,
              calculator: calculator,
            );

            final expectedParana = Map<String, dynamic>.from(
              event['parana'] as Map,
            );
            final label =
                '$locationId ${event['fast_date']} (${event['name']}, $fastDayType)';

            final startDiff = _minuteDiffOrNull(
              result.start,
              expectedParana['start'] as String?,
            );
            final preferredEndDiff = _minuteDiffOrNull(
              result.preferredEnd,
              expectedParana['preferred_end'] as String?,
            );
            final absoluteEndDiff = _minuteDiffOrNull(
              result.absoluteEnd,
              expectedParana['absolute_end'] as String?,
            );

            final statusMatches =
                result.preferredWindowStatus ==
                expectedParana['preferred_window_status'];

            final ok =
                (startDiff == null || startDiff <= 2) &&
                (preferredEndDiff == null || preferredEndDiff <= 2) &&
                (absoluteEndDiff == null || absoluteEndDiff <= 2) &&
                statusMatches;

            if (!ok) {
              mismatches.add(
                '$label: start_diff=$startDiff preferred_end_diff=$preferredEndDiff '
                'absolute_end_diff=$absoluteEndDiff status(dart=${result.preferredWindowStatus} '
                'web=${expectedParana['preferred_window_status']})',
              );
            }
          }
        }

        expect(
          checked,
          greaterThan(20),
          reason:
              'Expected a healthy sample of Ekadashi fast events in the fixture '
              '- got $checked. Re-run scripts/generate-mobile-fixtures.mjs?',
        );
        expect(
          mismatches,
          isEmpty,
          reason:
              '${mismatches.length}/$checked parana windows disagree with web:\n'
              '${mismatches.join('\n')}',
        );
      },
    );
  });

  group('Phase C - Ekadashi classification', () {
    test(
      'EkadashiClassifier reproduces the web fixture\'s fast days, no-fast '
      'notices, and parana windows for every sampled location',
      () {
        const calculator = PanchangaCalculator();
        final classifier = EkadashiClassifier(
          engineRules,
          calculator: calculator,
        );

        final casesByLocation = <String, List<Map<String, dynamic>>>{};
        for (final rawCase in fixtureCases) {
          final fixtureCase = Map<String, dynamic>.from(rawCase as Map);
          casesByLocation
              .putIfAbsent(fixtureCase['location_id'] as String, () => [])
              .add(fixtureCase);
        }

        final mismatches = <String>[];
        var fastsChecked = 0;
        var noticesChecked = 0;

        for (final entry in casesByLocation.entries) {
          final locationId = entry.key;
          final location = _locations[locationId];
          if (location == null) continue;
          final cases = entry.value;

          final dates = cases
              .map((c) => c['date'] as String)
              .toList(growable: false)
            ..sort();
          final minDate = _parseDate(dates.first);
          final maxDate = _parseDate(dates.last);
          final days = _buildDayRange(
            calculator: calculator,
            location: location,
            start: minDate.subtract(const Duration(days: 20)),
            end: maxDate.add(const Duration(days: 20)),
          );

          final result = classifier.classifyRange(days, location);

          for (final fixtureCase in cases) {
            for (final rawEvent in fixtureCase['events'] as List) {
              final event = Map<String, dynamic>.from(rawEvent as Map);
              final label = '$locationId ${fixtureCase['date']} (${event['name']})';

              if (event['type'] == 'ekadashi') {
                fastsChecked += 1;
                final fastDate = event['fast_date'] as String;
                final actual = result.fastsByFastDate[fastDate];
                if (actual == null) {
                  mismatches.add('$label: MISSING fast on $fastDate');
                  continue;
                }
                if (actual.classification != event['classification'] ||
                    actual.candidateDate != event['candidate_date'] ||
                    actual.fastDayType != event['fast_day_type'] ||
                    actual.paranaType != event['parana_type']) {
                  mismatches.add(
                    '$label: classification(dart=${actual.classification} '
                    'web=${event['classification']}) candidate_date(dart=${actual.candidateDate} '
                    'web=${event['candidate_date']}) fast_day_type(dart=${actual.fastDayType} '
                    'web=${event['fast_day_type']}) parana_type(dart=${actual.paranaType} '
                    'web=${event['parana_type']})',
                  );
                  continue;
                }
                final expectedParana = Map<String, dynamic>.from(
                  event['parana'] as Map,
                );
                final startDiff = _minuteDiffOrNull(
                  actual.parana.start,
                  expectedParana['start'] as String?,
                );
                final absoluteEndDiff = _minuteDiffOrNull(
                  actual.parana.absoluteEnd,
                  expectedParana['absolute_end'] as String?,
                );
                if ((startDiff != null && startDiff > 2) ||
                    (absoluteEndDiff != null && absoluteEndDiff > 2)) {
                  mismatches.add(
                    '$label: parana start_diff=$startDiff absolute_end_diff=$absoluteEndDiff',
                  );
                }
              } else if (event['type'] == 'ekadashi_notice') {
                noticesChecked += 1;
                final candidateDate = fixtureCase['date'] as String;
                final actual = result.noFastByCandidateDate[candidateDate];
                if (actual == null) {
                  mismatches.add(
                    '$label: MISSING no-fast notice on $candidateDate '
                    '(web reason=${event['candidate_no_fast_reason']})',
                  );
                  continue;
                }
                if (actual.reason != event['candidate_no_fast_reason']) {
                  mismatches.add(
                    '$label: no-fast reason mismatch dart=${actual.reason} '
                    'web=${event['candidate_no_fast_reason']}',
                  );
                }
              }
            }
          }
        }

        expect(
          fastsChecked,
          greaterThan(20),
          reason: 'Expected a healthy sample of Ekadashi fast events - got $fastsChecked.',
        );
        expect(
          noticesChecked,
          greaterThanOrEqualTo(5),
          reason: 'Expected a healthy sample of no-fast notices - got $noticesChecked.',
        );
        expect(
          mismatches,
          isEmpty,
          reason:
              '${mismatches.length} Ekadashi classification mismatches vs web:\n'
              '${mismatches.join('\n')}',
        );
      },
    );
  });
}

DateTime _parseDate(String iso) {
  final parts = iso.split('-').map(int.parse).toList(growable: false);
  return DateTime.utc(parts[0], parts[1], parts[2]);
}

List<PanchangaDay> _buildDayRange({
  required PanchangaCalculator calculator,
  required CalendarLocation location,
  required DateTime start,
  required DateTime end,
}) {
  final days = <PanchangaDay>[];
  var cursor = start;
  while (!cursor.isAfter(end)) {
    days.add(calculator.calculateDay(date: cursor, location: location));
    cursor = cursor.add(const Duration(days: 1));
  }
  return days;
}

/// Null-safe minute difference between a Dart DateTime and an ISO string
/// (or "not available"/null) from the fixture. Returns null when either
/// side is absent (both-absent is a pass, one-absent-one-present is
/// reported as a large diff by the caller's own null handling below).
int? _minuteDiffOrNull(DateTime? actual, String? expectedIso) {
  if (actual == null && (expectedIso == null)) return null;
  if (actual == null || expectedIso == null) return 999;
  final expected = DateTime.parse(expectedIso);
  return actual.difference(expected).inMinutes.abs();
}
